[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-backtrace = { version = "0.19", features = ["esp32s3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.5", features = ["esp32s3"] }
esp-hal = { version = "1.1", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.17", features = ["esp32s3"] }
games = { path = "../games" }
raylib_camp = { path = "../raylib_camp" }
